### PR TITLE
Remove end_of_line = crlf

### PR DESCRIPTION
**Pull request by kirkone**
LF is more common and allows plattform independent development.

### CODE REVIEW

**Comment by RehanSaeed** [comment]
More common on unix based systems. Windows uses CRLF. I recently blogged about this subject in the context of git:

https://rehansaeed.com/gitattributes-best-practices/

Perhaps this setting should just be removed, so git can deal with line endings depending on the operating system.

cc @henrygab.

**Comment by RehanSaeed** [comment]
Definately a major version change. Since we're using SemVer and upgrading this file means manually doing it, that should be sufficient for people to check the release notes.

Raised https://github.com/RehanSaeed/EditorConfig/pull/15 to add a link to the GitHub releases page for the release notes. Also created a [draft 1.3.0 release](https://github.com/RehanSaeed/EditorConfig/releases/tag/untagged-b06c42023c946f63fbfc).

**Comment by RehanSaeed** [comment]
Correct. You can now edit PR's in GitHub, so I've made that change.

**Comment by RehanSaeed** [comment]
@kirkone Are you happy with this change or do you see any problems?

**Comment by kirkone** [comment]
hi,

the only problem I see is that the editor will not have any influence on how the line endings will used.
When only git is used to get the file endings right this will only happen when a commit is done. This in my opinion is a strong binding to the git tooling.

When you for example develop in e Container or the WSL a correcting git commit will be too late.

Maybe we should add a comment line above to describe more what consequences this has.

**Comment by RehanSaeed** [comment]
Looks like the .editorconfig folks have thought about this:

>NOTE: if you want to use native line endings between different operating systems it is better not to set this option and leave that task to the VCS! In the future we might add a value like native for this scenario (https://github.com/editorconfig/editorconfig/issues/226).
https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties

A long discussion about this in https://github.com/editorconfig/editorconfig/issues/226. The result being that some people are removing this setting while others are using `LF`. I'm not sure I'm any clearer on where to go.

**Comment by RehanSaeed** [comment]
The Roslyn project doesn't set this https://github.com/dotnet/roslyn/blob/master/.editorconfig except for `.sh` bash files where it is set to `lf`. When it doubt, defer to another expert is where I'm at.

**Pull request merged**
