### PR TITLE
insert_final_newline = true

### PR DESCRIPTION
**Pull request by kirkone**
Having a newline at the end of each file is a common practice.

More details here:
https://stackoverflow.com/a/5813359/6526640
and here:
https://stackoverflow.com/a/729795/6526640

### CODE REVIEW

**Comment by RehanSaeed** [comment]
Interesting. This is another thing that Unix cares about more than Windows which as far as I know doesn't care about files ending with a new line.

Line 53 should be removed if we want to make this change. Thoughts @henrygab?

**Comment by RehanSaeed** [comment]
See my comment in https://github.com/RehanSaeed/EditorConfig/pull/14.

@henrygab What do you think about just adding a URL to the GitHub releases page, instead of actually adding the release notes directly into the file? This could get pretty long eventually.

**Comment by henrygab** [comment]
@RehanSaeed I just advise.  I prefer an all-in-one solution in the file.  However, a link to an official list of changes will work also.

**Comment by RehanSaeed** [comment]
Removed the second `insert_final_newline = true` that was for web related files given the first one affects all files now.

**Pull request merged**
