### PR TITLE
Code Style section does not use severity

### PR DESCRIPTION
**Pull request by henrygab**
See https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference#formatting-conventions
Most of the rules for formatting conventions have the following format:
rule_name = false|true
You specify either true (prefer this style) or
false (do not prefer this style). You do not specify a severity.

### CODE REVIEW

**Comment by RehanSaeed** [comment]
I don't get why some rules have a severity and others don't. Any more info on why that is? Perhaps we should raise an issue asking this question to the tooling team.

**Comment by RehanSaeed** [comment]
Merged. Thanks for this, much appreciated!

**Comment by RehanSaeed** [comment]
BTW, VS 15.8 came out with some new settings and also documented a few more. See the last commits and [this](https://blogs.msdn.microsoft.com/visualstudio/2018/08/14/visual-studio-2017-version-15-8/) for details.

**Comment by henrygab** [comment]
:thumbsup:

**Pull request merged**
