### PR TITLE
Add PowerShell files

### PR DESCRIPTION
**Pull request by jpawlowski**
This will add some simple lines for PowerShell scripting

### CODE REVIEW

**Comment by RehanSaeed** [comment]
Thanks for putting this together. Are we sure that PowerShell files require CRLF? Is there some documentation we can look at? Also, how does this work on Mac and Linux where LF is the standard?

**Comment by jpawlowski** [comment]
You may get an idea about how MSFT sees the topic here:
https://github.com/microsoft/Windows-Dev-Performance/issues/85

**Comment by RehanSaeed** [comment]
Since this setting is variable between operating systems, its might be best to leave it to Git to configure via a `.gitattributes` file like so from this repo:

https://github.com/RehanSaeed/EditorConfig/blob/ff57620c2e990828a33ad50413a115d5d9018877/.gitattributes#L1-L15

Here we rely on Git to automatically give us the correct line endings depending on the OS and then force certain files line endings where required by the file type.

**Comment by RehanSaeed** [comment]
People not using Git is (I hope and think) a rare scenario but in that case there may be a similar feature in the source control system they are using. If they are using no source control yet, then yes having some kind of default added to `.editorconfig` makes more sense and they should do that at the top level `*` selector. In this case, they will have to choose CRLF or LF depending on their OS of choice. This is also where the line ending settings in the `.editorconfig` you mention are useful.

On the other hand if they are using Git, then `.gitattributes` is the recommended approach to solve this problem and the settings you mention are not very useful.

**Comment by RehanSaeed** [comment]
Closing for now. Thanks for your input.

**Pull request closed without merging**
